
if ( typeof(Yesup) == "undefined" || ! Yesup.hasNetwork("clicksor") ) {
    document.write("<img src=\"http://serw.myroitracking.com/newServing/tracking_id.php?d=serw.clicksor.com&r=http%3A%2F%2Fserw.clicksor.com%2FnewServing%2Ftracking_id.php%3Fb%3D1%26\" width=\"1\" height=\"1\" />");
}


private_label_prefix = "clicksor";
clicksor_company_name = "Clicksor";
clicksor_static_host = "pub.clicksor.net";
clicksor_service = "serw.clicksor.com";
clicksor_image_base_url = "http://pub.clicksor.net/newServing/img/";
clicksor_search_base_url = "http://ads.clicksor.com/newServing/yesupSearch/web.php?q=";


clicksor_adhere_url = "http://signup.clicksor.com/advertise_here.php?nid=1&srid=26450781";
clicksor_widget_title = "Clicksor Connect";
clicksor_widget_title_link = "http://www.clicksor.com/connect-widget";

clicksor_pub_host = "admin.clicksor.com/publisher";
clicksor_nid=1;
clicksor_pid=308374;
clicksor_sid=508633;
clicksor_banner_adtype=5;
clicksor_default_banner_border="#B4D0DC";
clicksor_default_banner_bg="#ECF8FF";

if ( typeof(Yesup) == "undefined" || ! Yesup.hasNetwork("clicksor") ) {
    document.write("<iframe src=\"http://serw.clicksor.com/newServing/searchTrack.php?nid=1&sid=508633&random=1790946340\" width=\"1\" height=\"1\" frameborder=\"0\" scrolling=\"no\" style=\"position:absolute;z-index:9999301;\"></iframe>");
}

if ( typeof(Yesup) == "undefined" ) {
        document.write('<script type="text/javascript" src="http://pub.clicksor.net/newServing/js/show_ad.js"></script>');
    }  else {
    Yesup.Init();
}

// generated by www168 in 0 seconds